version: 2
sources:
  - name: raw_amazon
    database: ecommerce
    schema: raw_amazon
    tables:
      - name: customers
      - name: orders
      - name: products
      - name: order_reviews
      - name: order_items
      - name: product_category_name_translation
      
  - name: raw_etsy
    database: ecommerce
    schema: raw_etsy
    tables:
      - name: customers
      - name: orders
      - name: products
      - name: order_reviews
      - name: order_items
      - name: product_category_name_translation
      
  - name: raw_shopify
    database: ecommerce
    schema: raw_shopify
    tables:
      - name: customers
      - name: orders
      - name: products
      - name: order_reviews   
      - name: order_items   
      - name: product_category_name_translation
